services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    build:
      context: ./mosquitto/
      dockerfile: Dockerfile
    ports:
      - "8883:8883"
    restart: always

  influxdb2:
    container_name: influxdb2
    build:
      context: ./influxdb/
      dockerfile: Dockerfile
    ports:
      - 8086:8086

  grafana:
    container_name: grafana
    build:
      context: ./grafana/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  mqtt_consumer:
    container_name: mqtt_consumer
    build:
      context: ./mqtt_consumer/
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
      - influxdb2
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 8883
      INFLUXDB_HOST: influxdb2
      INFLUXDB_PORT: 8086
      INFLUXDB_DB: buckit
      INFLUXDB_TOKEN: MyInitialAdminToken0==
    restart: always
