services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./certs:/mosquitto
    ports:
      - "8883:8883"
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_CONFIG_PATH=/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  mqtt_consumer:
    build: ./mqtt_consumer
    container_name: mqtt_consumer
    depends_on:
      - mosquitto
      - influxdb
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=8883
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=your_database_name
    volumes:
      - ./certs:/certs
    restart: always

volumes:
  influxdb_data:
  grafana_data:
