services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./certs:/mosquitto
    ports:
      - "8883:8883"
    restart: always
